import type { SkillCategoryConfig, SkillItem } from "@/config/types";

export const skillsSectionConfig = {
  title: "Stack",
  categories: [
    { id: "languages", label: "Languages" },
    { id: "ai-stack", label: "AI Stack" },
    { id: "frameworks", label: "Frameworks" },
    { id: "backend", label: "Backend" },
    { id: "ai-tools", label: "AI Tools" },
    { id: "os", label: "OS" },
    { id: "other", label: "Other" },
  ] as SkillCategoryConfig[],
};

export const skillsConfig: SkillItem[] = [
  // Languages — what I code myself
  {
    id: "c",
    name: "C",
    icon: "c",
    category: "languages",
    order: 1,
    enabled: true,
  },
  {
    id: "cpp",
    name: "C++",
    icon: "cpp",
    category: "languages",
    order: 2,
    enabled: true,
  },
  {
    id: "python",
    name: "Python",
    icon: "python",
    category: "languages",
    order: 3,
    enabled: true,
  },

  // AI Stack — what I use to build faster
  {
    id: "c-ai",
    name: "C",
    icon: "c",
    category: "ai-stack",
    order: 4,
    enabled: true,
  },
  {
    id: "cpp-ai",
    name: "C++",
    icon: "cpp",
    category: "ai-stack",
    order: 5,
    enabled: true,
  },
  {
    id: "python-ai",
    name: "Python",
    icon: "python",
    category: "ai-stack",
    order: 6,
    enabled: true,
  },
  {
    id: "rust",
    name: "Rust",
    icon: "rust",
    category: "ai-stack",
    order: 7,
    enabled: true,
  },
  {
    id: "typescript",
    name: "TypeScript",
    icon: "typescript",
    category: "ai-stack",
    order: 8,
    enabled: true,
  },
  {
    id: "javascript",
    name: "JavaScript",
    icon: "javascript",
    category: "ai-stack",
    order: 9,
    enabled: true,
  },
  {
    id: "html",
    name: "HTML",
    icon: "html",
    category: "ai-stack",
    order: 10,
    enabled: true,
  },
  {
    id: "css",
    name: "CSS",
    icon: "css",
    category: "ai-stack",
    order: 11,
    enabled: true,
  },
  {
    id: "svelte",
    name: "Svelte",
    icon: "svelte",
    category: "ai-stack",
    order: 12,
    enabled: true,
  },
  {
    id: "everything",
    name: "EVERYTHING",
    icon: "everything",
    category: "ai-stack",
    order: 13,
    enabled: true,
  },
  // Frameworks
  {
    id: "react",
    name: "React",
    icon: "react",
    category: "frameworks",
    order: 13,
    enabled: true,
  },
  {
    id: "nextjs",
    name: "Next.js",
    icon: "nextjs",
    category: "frameworks",
    order: 14,
    enabled: true,
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    icon: "tailwind",
    category: "frameworks",
    order: 15,
    enabled: true,
  },
  {
    id: "shadcn",
    name: "shadcn/ui",
    icon: "shadcn",
    category: "frameworks",
    order: 16,
    enabled: true,
  },

  // Backend
  {
    id: "supabase",
    name: "Supabase",
    icon: "supabase",
    category: "backend",
    order: 17,
    enabled: true,
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    icon: "postgresql",
    category: "backend",
    order: 18,
    enabled: true,
  },
  {
    id: "sqlite",
    name: "SQLite",
    icon: "sqlite",
    category: "backend",
    order: 19,
    enabled: true,
  },

  // AI Tools
  {
    id: "chatgpt",
    name: "ChatGPT",
    icon: "chatgpt",
    category: "ai-tools",
    order: 20,
    enabled: true,
  },
  {
    id: "claude",
    name: "Claude",
    icon: "claude",
    category: "ai-tools",
    order: 21,
    enabled: true,
  },
  {
    id: "gemini",
    name: "Gemini",
    icon: "gemini",
    category: "ai-tools",
    order: 22,
    enabled: true,
  },
  {
    id: "opencode",
    name: "OpenCode",
    icon: "opencode",
    category: "ai-tools",
    order: 23,
    enabled: true,
  },
  // OS
  {
    id: "archlinux",
    name: "Arch Linux",
    icon: "archlinux",
    category: "os",
    order: 24,
    enabled: true,
  },
  {
    id: "windows",
    name: "Windows 11",
    icon: "windows",
    category: "os",
    order: 25,
    enabled: true,
  },
  // Other
  {
    id: "web3",
    name: "Web3",
    icon: "web3",
    category: "other",
    order: 26,
    enabled: true,
  },
];
